apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: simondaniel254/ip4-frontend:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: http://10.132.0.7:5000
